import {test,expect} from '@playwright/test';
test('assembled model rebuilds from measurements and exports the current printable part',async({page})=>{
 test.setTimeout(180000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');
 await expect(page.locator('#report')).toContainText('Digital assembly: PASS',{timeout:90000});
 await expect(page.locator('#report')).toContainText('8 printed parts');
 await expect(page.locator('#report')).toContainText('24 printed push-pins');
 await expect(page.getByText('Screws',{exact:true})).toHaveCount(0);
 await page.screenshot({path:'out/case-closed.png'});
 await page.locator('#xray').check();await page.screenshot({path:'out/workbench.png'});
 await page.locator('#explode').check();await page.screenshot({path:'out/workbench-exploded.png'});
 const before=await page.locator('#report').textContent();
 await page.locator('#part').selectOption('battery');
 await page.getByRole('spinbutton',{name:'battery.thickness',exact:true}).fill('8.3');
 await page.getByRole('spinbutton',{name:'battery.thickness',exact:true}).press('Tab');
 await expect(page.locator('#status')).toContainText('Rebuilding',{timeout:10000});
 await expect(page.locator('#report')).toContainText('Digital assembly: PASS',{timeout:90000});
 expect(await page.locator('#report').textContent()).not.toBe(before);
 const save=page.waitForEvent('download');await page.getByRole('button',{name:'Save parameters'}).click();const parameters=await save;
 await page.getByRole('button',{name:'Reset design'}).click();await expect(page.locator('#report')).toContainText('Digital assembly: PASS',{timeout:90000});
 await page.locator('#load').setInputFiles((await parameters.path())!);await expect(page.locator('#report')).toContainText('Digital assembly: PASS',{timeout:90000});
 await expect(page.getByRole('spinbutton',{name:'battery.thickness',exact:true})).toHaveValue('8.3');
 const pin=page.locator('#print-part option').filter({hasText:'Printed split push-pin 8 mm'}).first();
 await page.locator('#print-part').selectOption((await pin.getAttribute('value'))!);
 const stl=page.waitForEvent('download');await page.getByRole('button',{name:'Download STL',exact:true}).click();expect((await stl).suggestedFilename()).toMatch(/\.stl$/);
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Fit view'}).click();await page.screenshot({path:'out/workbench-mobile.png',fullPage:true});
 expect(errors).toEqual([]);
});
