[build]
target = "xtensa-esp32-espidf"

[unstable]
build-std = ["std", "panic_abort"]

[target.xtensa-esp32-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor"

[env]
MCU = "esp32"
ESP_IDF_VERSION = "v5.2"
ESP_IDF_SYS_ROOT_CRATE = "ceridwen-esp32"
